Repository Black-Kamelia/Sprinkler, pull requests merged in 2023-07, with the labels that each got.

#21 Update CI
  Jenkinsfile
  README.md
Labels: Enhancement

#31 29 mistakes in guide documentation
  README.md
  binary-transcoders/README.md
  utils/README.md
Labels: Documentation

#33 30 sprinkler utils is not properly transitive in sprinkler binary transcoders
  README.md
  binary-transcoders/CHANGELOG.md
  binary-transcoders/README.md
  binary-transcoders/build.gradle.kts
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/encoder/composer/EncodingScope.kt
  gradle.properties
  jvm-bridge/CHANGELOG.md
  jvm-bridge/README.md
  jvm-bridge/src/main/java/com/kamelia/sprinkler/bridge/KotlinDslAdapter.java
  jvm-bridge/src/test/java/com/kamelia/sprinkler/bridge/KotlinDslAdapterTest.java
  readonly-collections/CHANGELOG.md
  readonly-collections/README.md
  settings.gradle.kts
  utils/CHANGELOG.md
  utils/README.md
  utils/src/test/java/com/kamelia/sprinkler/util/jvmlambda/KotlinDslAdapterTest.java
  utils/src/test/kotlin/com/kamelia/sprinkler/util/jvmlambda/DummyPerson.kt
Labels: Bug fix, Enhancement
