Repository Black-Kamelia/Sprinkler, pull requests merged in 2023-08, with the labels that each got.

#36 DecoderInput::read doc clarification & read EOF returns -1 instead of 0
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/ConstantSizedItemDecoder.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/DecoderInput.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/PrefixedSizeItemDecoder.kt
  binary-transcoders/src/test/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/DecoderInputTest.kt
Labels: Bug fix, Documentation, Enhancement

#38 Add the setValue operator for mutable boxes
  utils/src/main/kotlin/com/kamelia/sprinkler/util/Box.kt
  utils/src/test/kotlin/com/kamelia/sprinkler/util/BoxTest.kt
Labels: Enhancement

#39 Changelog update
  binary-transcoders/CHANGELOG.md
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/ConstantArityReductionDecoder.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/DecoderInput.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/MarkerEndedReductionDecoder.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/PrefixedArityReductionDecoder.kt
  binary-transcoders/src/test/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/DecoderInputTest.kt
  jvm-bridge/README.md
  jvm-bridge/src/main/java/com/kamelia/sprinkler/bridge/LambdaAdapters.java
  jvm-bridge/src/main/kotlin/com/kamelia/sprinkler/bridge/CollectorExtensions.kt
  jvm-bridge/src/main/kotlin/com/kamelia/sprinkler/bridge/InvokeExtensions.kt
  jvm-bridge/src/test/java/com/kamelia/sprinkler/bridge/KotlinDslAdapterTest.java
  jvm-bridge/src/test/java/com/kamelia/sprinkler/bridge/LambdaAdaptersTest.java
  jvm-bridge/src/test/kotlin/com/kamelia/sprinkler/bridge/CollectorExtensionsTest.kt
  jvm-bridge/src/test/kotlin/com/kamelia/sprinkler/bridge/ExtensionsTest.kt
  utils/CHANGELOG.md
  utils/README.md
  utils/src/main/kotlin/com/kamelia/sprinkler/util/Typing.kt
  utils/src/test/kotlin/com/kamelia/sprinkler/util/CloseableScopeTest.kt
  utils/src/test/kotlin/com/kamelia/sprinkler/util/TypingTest.kt
Labels: Documentation

#41 Release
  README.md
  binary-transcoders/CHANGELOG.md
  binary-transcoders/README.md
  binary-transcoders/build.gradle.kts
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/ConstantArityReductionDecoder.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/ConstantSizedItemDecoder.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/DecoderInput.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/MarkerEndedReductionDecoder.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/PrefixedArityReductionDecoder.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/PrefixedSizeItemDecoder.kt
  binary-transcoders/src/main/kotlin/com/kamelia/sprinkler/transcoder/binary/encoder/composer/EncodingScope.kt
  binary-transcoders/src/test/kotlin/com/kamelia/sprinkler/transcoder/binary/decoder/core/DecoderInputTest.kt
  gradle.properties
  jvm-bridge/CHANGELOG.md
  jvm-bridge/README.md
  jvm-bridge/src/main/java/com/kamelia/sprinkler/bridge/KotlinDslAdapter.java
  jvm-bridge/src/main/java/com/kamelia/sprinkler/bridge/LambdaAdapters.java
  jvm-bridge/src/main/kotlin/com/kamelia/sprinkler/bridge/CollectorExtensions.kt
  jvm-bridge/src/main/kotlin/com/kamelia/sprinkler/bridge/InvokeExtensions.kt
  jvm-bridge/src/test/java/com/kamelia/sprinkler/bridge/KotlinDslAdapterTest.java
  jvm-bridge/src/test/java/com/kamelia/sprinkler/bridge/LambdaAdaptersTest.java
  jvm-bridge/src/test/kotlin/com/kamelia/sprinkler/bridge/CollectorExtensionsTest.kt
  jvm-bridge/src/test/kotlin/com/kamelia/sprinkler/bridge/ExtensionsTest.kt
  readonly-collections/CHANGELOG.md
  readonly-collections/README.md
  settings.gradle.kts
  utils/CHANGELOG.md
  utils/README.md
  utils/src/main/kotlin/com/kamelia/sprinkler/util/Box.kt
  utils/src/main/kotlin/com/kamelia/sprinkler/util/Typing.kt
  utils/src/test/java/com/kamelia/sprinkler/util/jvmlambda/KotlinDslAdapterTest.java
  utils/src/test/kotlin/com/kamelia/sprinkler/util/BoxTest.kt
  utils/src/test/kotlin/com/kamelia/sprinkler/util/CloseableScopeTest.kt
  utils/src/test/kotlin/com/kamelia/sprinkler/util/TypingTest.kt
  utils/src/test/kotlin/com/kamelia/sprinkler/util/jvmlambda/DummyPerson.kt
Labels: Bug fix, Documentation, Enhancement

#47 45 utils string interpolation api
  utils/CHANGELOG.md
  utils/README.md
  utils/src/main/kotlin/com/kamelia/sprinkler/util/Exceptions.kt
  utils/src/main/kotlin/com/kamelia/sprinkler/util/Interpolations.kt
  utils/src/test/kotlin/com/kamelia/sprinkler/util/ExceptionsTest.kt
  utils/src/test/kotlin/com/kamelia/sprinkler/util/InterpolationsTest.kt
Labels: Enhancement
